package com.voidking.struts2_hibernate.model;
// default package
// Generated 2015-5-23 0:27:57 by Hibernate Tools 3.4.0.CR1

/**
 * Dlb generated by hbm2java
 */
public class Dlb implements java.io.Serializable {

	private int id;
	private String xh;
	private String kl;

	public Dlb() {
	}

	public Dlb(int id, String xh) {
		this.id = id;
		this.xh = xh;
	}

	public Dlb(int id, String xh, String kl) {
		this.id = id;
		this.xh = xh;
		this.kl = kl;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getXh() {
		return this.xh;
	}

	public void setXh(String xh) {
		this.xh = xh;
	}

	public String getKl() {
		return this.kl;
	}

	public void setKl(String kl) {
		this.kl = kl;
	}

}
