package com.voidking.struts2_hibernate.model;

import java.util.HashSet;
// default package
// Generated 2015-5-23 0:27:57 by Hibernate Tools 3.4.0.CR1
import java.util.Set;

/**
 * Kcb generated by hbm2java
 */
public class Kcb implements java.io.Serializable {

	private String kch;
	private String kcm;
	private Short kxxq;
	private Integer xs;
	private Integer xf;
	private Set xss = new HashSet();

	public Kcb() {
	}

	public Kcb(String kch) {
		this.kch = kch;
	}

	public Kcb(String kch, String kcm, Short kxxq, Integer xs, Integer xf) {
		this.kch = kch;
		this.kcm = kcm;
		this.kxxq = kxxq;
		this.xs = xs;
		this.xf = xf;
	}

	public String getKch() {
		return this.kch;
	}

	public void setKch(String kch) {
		this.kch = kch;
	}

	public String getKcm() {
		return this.kcm;
	}

	public void setKcm(String kcm) {
		this.kcm = kcm;
	}

	public Short getKxxq() {
		return this.kxxq;
	}

	public void setKxxq(Short kxxq) {
		this.kxxq = kxxq;
	}

	public Integer getXs() {
		return this.xs;
	}

	public void setXs(Integer xs) {
		this.xs = xs;
	}

	public Integer getXf() {
		return this.xf;
	}

	public void setXf(Integer xf) {
		this.xf = xf;
	}

	public Set getXss() {
		return xss;
	}

	public void setXss(Set xss) {
		this.xss = xss;
	}

}
