package com.voidking.struts2_hibernate.model;
// default package
// Generated 2015-5-23 0:27:57 by Hibernate Tools 3.4.0.CR1

/**
 * XsKcb generated by hbm2java
 */
public class XsKcb implements java.io.Serializable {

	private XsKcbId id;

	public XsKcb() {
	}

	public XsKcb(XsKcbId id) {
		this.id = id;
	}

	public XsKcbId getId() {
		return this.id;
	}

	public void setId(XsKcbId id) {
		this.id = id;
	}

}
